{
 "title": "Netatmo",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Quick stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Humidity inside",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Humidity",
     "query": "SELECT mean(\"value\") FROM \"CO2\" WHERE $timeFilter AND \"station_name_name\" =~ /^$station_name$/ GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Innenraum" }
     ]
    }
   ]
  },
  {
   "title": "Temperature inside",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "query": "SELECT last(\"value\") FROM \"Temperature\" WHERE \"station_name_name\" =~ /^$station_name$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Innenraum" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "format": "pressurembar",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Pressure",
     "query": "SELECT last(\"value\") FROM \"AbsolutePressure\" WHERE $timeFilter AND \"station_name_name\" =~ /^$station_name$/ GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Innenraum" }
     ]
    }
   ]
  },
  {
   "title": "Mean CO2 level inside",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "format": "ppm",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CO2",
     "query": "SELECT mean(\"value\") FROM \"CO2\" WHERE $timeFilter AND \"station_name_name\" =~ /^$station_name$/ GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Innenraum" }
     ]
    }
   ]
  },
  {
   "title": "Temperature outside",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "query": "SELECT last(\"value\") FROM \"Temperature\" WHERE \"station_name_name\" =~ /^$station_name$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Aussenraum" }
     ]
    }
   ]
  },
  {
   "title": "Inside Noise",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "format": "dB",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Noise",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Innenraum" }
     ]
    }
   ]
  },
  {
   "title": "Humidity outside",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Humidity",
     "query": "SELECT mean(\"value\") FROM \"CO2\" WHERE $timeFilter AND \"station_name_name\" =~ /^$station_name$/ GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Aussenraum" }
     ]
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Temperature inside",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature outside - $tag_station_name_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "station_name_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "query": "SELECT mean(\"value\") FROM \"Temperature\" WHERE \"module_type\" = 'Aussenraum' AND \"station_name_name\" =~ /^$station_name$/ AND $timeFilter GROUP BY time($interval), \"station_name_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Innenraum" }
     ]
    }
   ]
  },
  {
   "title": "Temperature outside",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature outside - $tag_station_name_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "station_name_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "query": "SELECT mean(\"value\") FROM \"Temperature\" WHERE \"module_type\" = 'Aussenraum' AND \"station_name_name\" =~ /^$station_name$/ AND $timeFilter GROUP BY time($interval), \"station_name_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Aussenraum" }
     ]
    }
   ]
  },
  { "title": "CO2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CO2 level inside",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "alias": "CO2 - $tag_module_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "module_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2",
     "query": "SELECT mean(\"value\") FROM \"CO2\" WHERE \"station_name_name\" =~ /^$station_name$/ AND $timeFilter GROUP BY time($interval), \"module_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Innenraum" }
     ]
    }
   ]
  },
  { "title": "Pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "pressurembar" }
   ],
   "targets": [
    {
     "alias": "Pressure - $tag_module_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "module_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Pressure",
     "query": "SELECT mean(\"value\") FROM \"Pressure\" WHERE \"station_name_name\" =~ /^$station_name$/ AND $timeFilter GROUP BY time($interval), \"module_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Innenraum" }
     ]
    },
    {
     "alias": "Absolute Pressure - $tag_module_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "module_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "absolutePressure",
     "query": "SELECT mean(\"value\") FROM \"Pressure\" WHERE \"station_name_name\" =~ /^$station_name$/ AND $timeFilter GROUP BY time($interval), \"module_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Innenraum" }
     ]
    }
   ]
  },
  { "title": "Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Humidity levels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Humidity - Innenraums",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "module_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Humidity",
     "query": "SELECT mean(\"value\") FROM \"Humidity\" WHERE \"station_name_name\" =~ /^$station_name$/ AND $timeFilter GROUP BY time($interval), \"module_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Innenraum" }
     ]
    },
    {
     "alias": "Humidity - Aussenraums",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "module_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Humidity",
     "query": "SELECT mean(\"value\") FROM \"Humidity\" WHERE \"station_name_name\" =~ /^$station_name$/ AND $timeFilter GROUP BY time($interval), \"module_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Aussenraum" }
     ]
    }
   ]
  },
  { "title": "Noise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Noise level inside",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "Noise level - $tag_module_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "module_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Noise",
     "query": "SELECT mean(\"value\") FROM \"Noise\" WHERE \"station_name_name\" =~ /^$station_name$/ AND $timeFilter GROUP BY time($interval), \"module_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=", "value": "Kastel" },
      { "condition": "AND", "key": "module_name", "operator": "=", "value": "Innenraum" }
     ]
    }
   ]
  }
 ]
}